### ISSUE TITLE
Output matrix "materials" size is erroneous for some domain/spatial step configurations 

### ISSUE THREAD

**Issue by qgoestch** [nicolas-f/FastVoxel#2]
Using the function `voxelizator.load_ply_model()`, some configuration leads to an incorrect filling of the matrix materials. The computation time in those situations increases quantitatively. Below, a test code is provided. In the case `bug = True`, the configuration leads to a (2913 x 2913 x 2913) matrix, whereas in the case `bug = False`, everything works just fine. The .ply file is attached to the issue as a .txt. 

    import sys
    import os
    from fastvoxel import fastvoxel as fv
    from fastvoxel import vec3, ivec3, np_voxel
    import numpy as np
    import time

    def voxelize_domain(DeltaL, filename, coords_point, data_filt):
        print("\n\nVoxelization...")
        deb = time.time()
        # Initialize the voxelisation with a precision in meter
        voxelizator = fv.TriangleScalarFieldCreator(DeltaL)
        # Load PLY polygonal file
        print("\tLoading 3D model...")
        if not voxelizator.load_ply_model(filename):
            raise (ValueError("Could not load ply file."))
        fin = time.time() - deb
        print("\tModel loaded  (in %.3f s)!" % (fin))
        # Extract the cell adress i,j,k values corresponding to the position of the source
        cellid = voxelizator.get_cell_id_by_coord(vec3(coords_point[0], coords_point[1], coords_point[2]))
        # Get the corresponding volume id
        outdoorvol = voxelizator.get_matrix_value(cellid)
        # Extract the boundary of this volume
        minv = fv.ivec3()
        maxv = fv.ivec3()
        voxelizator.get_cell_value_boundaries(minv, maxv, outdoorvol)
        minv -= fv.ivec3(2, 2, 2)
        maxv += fv.ivec3(2, 2, 2)
        extract_shape = maxv - minv
        print("\tMatrix Size: %ix%ix%i" % (extract_shape[0], extract_shape[1], extract_shape[2]))
        # Build the voxel matrix
        print("\tSpatial step: %.3f" % (DeltaL))
        materials = np_voxel.np_voxel(voxelizator, shape=(extract_shape[0], extract_shape[1], extract_shape[2]),
                                      range_beg=(minv[0], minv[1], minv[2]))
        nbmarkers = voxelizator.get_first_volume_index() + voxelizator.get_volume_count()
        data_filt = np.asarray(data_filt, dtype='int16')
        prev_filt = np.asarray([data + 10 for data in data_filt], dtype='int16')
        materials.set_filter(prev_filt)
        for n in range(len(data_filt)):
            print("\t\tBoundary %i: %i" % (n, data_filt[n]))
        materials.set_filter(data_filt)
        nbmarkers = len(np.unique(data_filt))
        print(f"\t{nbmarkers} markers detected")
        # plot_3D_array_slices(materials[:, :, :], DeltaL, extract_shape, nbmarkers, 5)
        print("...Voxelizator ready!")
        print(f"...Voxelizaton done in {fin} s!")
        return voxelizator, materials, nbmarkers, minv, maxv
    
    
    def FastVoxelBug(bug):
        sys.path.append(os.path.abspath('.'))
        if bug:
            DL = 0.0344239352943342  # Corresponds to N=10 for fmax = 1000 Hz
        else:
            DL = 0.038248816993704665  # Corresponds to N=9, works with N=11 : DL = 0.03129448663121291
        domain_filename = 'boxdisp1x100x70.mat.ply'
        coords_point_in_air = (0.45, 5, 5)
        data_filt = [0, -1, 1]
        voxelizator, materials, nbmarkers, minv, maxv = voxelize_domain(DL, domain_filename,
                                                                        coords_point_in_air, data_filt)
        print(np.shape(materials))
    
    
    if __name__ == '__main__':
        FastVoxelBug(bug=True)

Thank you in advance for trying to solve this problem! 

Quentin 
[boxdisp1x100x70.mat.txt](https://github.com/nicolas-f/FastVoxel/files/8893042/boxdisp1x100x70.mat.txt)

**Comment by nicolas-f** [comment]
FastVoxel was using float type. The issue is precision of float. I have replaced to double and there is 2 domains now.

**Comment by nicolas-f** [comment]
should be ok now.
vec3 has been rename to dvec3
if you don't want to replace all references you can do that:
```python
from fastvoxel import dvec3 as vec3
```

**Comment by qgoestch** [comment]
Thanks for solving this issue !
